
// Global Vue instance for shared data
const indexApp = new Vue({
    data: {
        upcomingTrips: [],
    },
});

// Create a Vue instance for the "index.html" page
new Vue({
    el: '#app',
    data: {
        upcomingTrips: indexApp.upcomingTrips,
    },
});

// Create a Vue instance for the "library.html" page
new Vue({
    el: '#app-library',
    data: {
        searchQuery: '',
        selectedCard: null,
        descriptionInput: '',
        cards: [
            {
                id: 1,
                title: 'Afghanistan',
                image: 'Images/Afghanistan.png',
                description: '',
            },
            {
                id: 2,
                title: 'Albania',
                image: 'Images/Albania.png',
                description: '',
            },
            {
                id: 3,
                title: 'Algeria',
                image: 'Images/Algeria.png',
                description: '',
            },
            {
                id: 4,
                title: 'Andorra',
                image: 'Images/Andorra.png',
                description: '',
            },
            {
                id: 5,
                title: 'Angola',
                image: 'Images/Angola.png',
                description: '',
            },
            {
                id: 6,
                title: 'Antigua',
                image: 'Images/Antigua.png',
                description: '',
            },
            {
                id: 7,
                title: 'Argentina',
                image: 'Images/Argentina.png',
                description: '',
            },
            {
                id: 8,
                title: 'Armenia',
                image: 'Images/Armenia.png',
                description: '',
            },
            {
                id: 9,
                title: 'Australia',
                image: 'Images/Australia.png',
                description: '',
            },
            {
                id: 10,
                title: 'Austria',
                image: 'Images/Austria.png',
                description: '',
            },
            {
                id: 11,
                title: 'Azerbaijan',
                image: 'Images/Azerbaijan.png',
                description: '',
            },
            {
                id: 12,
                title: 'Bahamas',
                image: 'Images/Bahamas.png',
                description: '',
            },
            {
                id: 13,
                title: 'Bahrain',
                image: 'Images/Bahrain.png',
                description: '',
            },
            {
                id: 14,
                title: 'Bangladesh',
                image: 'Images/Bangladesh.png',
                description: '',
            },
            {
                id: 15,
                title: 'Barbados',
                image: 'Images/Barbados.png',
                description: '',
            },
            {
                id: 16,
                title: 'Belarus',
                image: 'Images/Belarus.png',
                description: '',
            },
            {
                id: 17,
                title: 'Belgium',
                image: 'Images/Belgium.png',
                description: '',
            },
            {
                id: 18,
                title: 'Belize',
                image: 'Images/Belize.png',
                description: '',
            },
            {
                id: 19,
                title: 'Benin',
                image: 'Images/Benin.png',
                description: '',
            },
            {
                id: 20,
                title: 'Bhutan',
                image: 'Images/Bhutan.png',
                description: '',
            },
            {
                id: 21,
                title: 'Bolivia',
                image: 'Images/Bolivia.png',
                description: '',
            },
            {
                id: 22,
                title: 'Bosnia and Herzegovina',
                image: 'Images/Bosnia-and-Herzegovina.png',
                description: '',
            },
            {
                id: 23,
                title: 'Botswana',
                image: 'Images/Botswana.png',
                description: '',
            },
            {
                id: 24,
                title: 'Brazil',
                image: 'Images/Brazil.png',
                description: '',
            },
            {
                id: 25,
                title: 'Brunei',
                image: 'Images/Brunei.png',
                description: '',
            },
            {
                id: 26,
                title: 'Bulgaria',
                image: 'Images/Bulgaria.png',
                description: '',
            },
            {
                id: 27,
                title: 'Burkina Faso',
                image: 'Images/Burkina-Faso.png',
                description: '',
            },
            {
                id: 28,
                title: 'Burundi',
                image: 'Images/Burundi.png',
                description: '',
            },
            {
                id: 29,
                title: 'Cabo Verde',
                image: 'Images/Cabo-Verde.png',
                description: '',
            },
            {
                id: 30,
                title: 'Cambodia',
                image: 'Images/Cambodia.png',
                description: '',
            },
            {
                id: 31,
                title: 'Cameroon',
                image: 'Images/Cameroon.png',
                description: '',
            },
            {
                id: 32,
                title: 'Canada',
                image: 'Images/Canada.png',
                description: '',
            },
            {
                id: 33,
                title: 'Central African Republic',
                image: 'Images/Central-African-Republic.png',
                description: '',
            },
            {
                id: 34,
                title: 'Chad',
                image: 'Images/Chad.png',
                description: '',
            },
            {
                id: 35,
                title: 'Chile',
                image: 'Images/Chile.png',
                description: '',
            },
            {
                id: 36,
                title: 'China',
                image: 'Images/China.png',
                description: '',
            },
            {
                id: 37,
                title: 'Colombia',
                image: 'Images/Colombia.png',
                description: '',
            },
            {
                id: 38,
                title: 'Comoros',
                image: 'Images/Comoros.png',
                description: '',
            },
            {
                id: 39,
                title: 'Costa Rica',
                image: 'Images/Costa-Rica.png',
                description: '',
            },
            {
                id: 40,
                title: 'Cote dIvoire',
                image: 'Images/Cote-dIvoire.png',
                description: '',
            },
            {
                id: 41,
                title: 'Croatia',
                image: 'Images/Croatia.png',
                description: '',
            },
            {
                id: 42,
                title: 'Cuba',
                image: 'Images/Cuba.png',
                description: '',
            },
            {
                id: 43,
                title: 'Cyprus',
                image: 'Images/Cyprus.png',
                description: '',
            },
            {
                id: 44,
                title: 'Czechia',
                image: 'Images/Czechia.png',
                description: '',
            },
            {
                id: 45,
                title: 'Democratic Republic of Congo',
                image: 'Images/Democratic-Republic-of-Congo.png',
                description: '',
            },
            {
                id: 46,
                title: 'Denmark',
                image: 'Images/Denmark.png',
                description: '',
            },
            {
                id: 47,
                title: 'Djibouti',
                image: 'Images/Djibouti.png',
                description: '',
            },
            {
                id: 48,
                title: 'Dominica',
                image: 'Images/Dominica.png',
                description: '',
            },
            {
                id: 49,
                title: 'Dominican Republic',
                image: 'Images/Dominican-Republic.png',
                description: '',
            },
            {
                id: 50,
                title: 'Ecuador',
                image: 'Images/Ecuador.png',
                description: '',
            },
            {
                id: 51,
                title: 'Egypt',
                image: 'Images/Egypt.png',
                description: '',
            },
            {
                id: 52,
                title: 'El Salvador',
                image: 'Images/El-Salvador.png',
                description: '',
            },
            {
                id: 53,
                title: 'Equatorial Guinea',
                image: 'Images/Equatorial-Guinea.png',
                description: '',
            },
            {
                id: 54,
                title: 'Eritrea',
                image: 'Images/Eritrea.png',
                description: '',
            },
            {
                id: 55,
                title: 'Estonia',
                image: 'Images/Estonia.png',
                description: '',
            },
            {
                id: 56,
                title: 'Eswatini',
                image: 'Images/Eswatini.png',
                description: '',
            },
            {
                id: 57,
                title: 'Ethiopia',
                image: 'Images/Ethiopia.png',
                description: '',
            },
            {
                id: 58,
                title: 'Fiji',
                image: 'Images/Fiji.png',
                description: '',
            },
            {
                id: 59,
                title: 'Finland',
                image: 'Images/Finland.png',
                description: '',
            },
            {
                id: 60,
                title: 'France',
                image: 'Images/France.png',
                description: '',
            },
            {
                id: 61,
                title: 'Gabon',
                image: 'Images/Gabon.png',
                description: '',
            },
            {
                id: 62,
                title: 'Gambia',
                image: 'Images/Gambia.png',
                description: '',
            },
            {
                id: 63,
                title: 'Georgia',
                image: 'Images/Georgia.png',
                description: '',
            },
            {
                id: 64,
                title: 'Germany',
                image: 'Images/Germany.png',
                description: '',
            },
            {
                id: 65,
                title: 'Ghana',
                image: 'Images/Ghana.png',
                description: '',
            },
            {
                id: 66,
                title: 'Greece',
                image: 'Images/Greece.png',
                description: '',
            },
            {
                id: 67,
                title: 'Grenada',
                image: 'Images/Grenada.png',
                description: '',
            },
            {
                id: 68,
                title: 'Guatemala',
                image: 'Images/Guatemala.png',
                description: '',
            },
            {
                id: 69,
                title: 'Guinea',
                image: 'Images/Guinea.png',
                description: '',
            },
            {
                id: 70,
                title: 'Guinea Bissau',
                image: 'Images/Guinea-Bissau.png',
                description: '',
            },
            {
                id: 71,
                title: 'Guyana',
                image: 'Images/Guyana.png',
                description: '',
            },
            {
                id: 72,
                title: 'Haiti',
                image: 'Images/Haiti.png',
                description: '',
            },
            {
                id: 73,
                title: 'Honduras',
                image: 'Images/Honduras.png',
                description: '',
            },
            {
                id: 74,
                title: 'Hungary',
                image: 'Images/Hungary.png',
                description: '',
            },
            {
                id: 75,
                title: 'Iceland',
                image: 'Images/Iceland.png',
                description: '',
            },
            {
                id: 76,
                title: 'India',
                image: 'Images/India.png',
                description: '',
            },
            {
                id: 77,
                title: 'Indonesia',
                image: 'Images/Indonesia.png',
                description: '',
            },
            {
                id: 78,
                title: 'Iran',
                image: 'Images/Iran.png',
                description: '',
            },
            {
                id: 79,
                title: 'Iraq',
                image: 'Images/Iraq.png',
                description: '',
            },
            {
                id: 80,
                title: 'Ireland',
                image: 'Images/Ireland.png',
                description: '',
            },
            {
                id: 81,
                title: 'Israel',
                image: 'Images/Israel.png',
                description: '',
            },
            {
                id: 82,
                title: 'Italy',
                image: 'Images/Italy.png',
                description: '',
            },
            {
                id: 83,
                title: 'Jamaica',
                image: 'Images/Jamaica.png',
                description: '',
            },
            {
                id: 84,
                title: 'Japan',
                image: 'Images/Japan.png',
                description: '',
            },
            {
                id: 85,
                title: 'Jordan',
                image: 'Images/Jordan.png',
                description: '',
            },
            {
                id: 86,
                title: 'Kazakhstan',
                image: 'Images/Kazakhstan.png',
                description: '',
            },
            {
                id: 87,
                title: 'Kenya',
                image: 'Images/Kenya.png',
                description: '',
            },
            {
                id: 88,
                title: 'Kiribati',
                image: 'Images/Kiribati.png',
                description: '',
            },
            {
                id: 89,
                title: 'Kosovo',
                image: 'Images/Kosovo.png',
                description: '',
            },
            {
                id: 90,
                title: 'Kuwait',
                image: 'Images/Kuwait.png',
                description: '',
            },
            {
                id: 91,
                title: 'Kyrgyzstan',
                image: 'Images/Kyrgyzstan.png',
                description: '',
            },
            {
                id: 92,
                title: 'Laos',
                image: 'Images/Laos.png',
                description: '',
            },
            {
                id: 93,
                title: 'Latvia',
                image: 'Images/Latvia.png',
                description: '',
            },
            {
                id: 94,
                title: 'Lebanon',
                image: 'Images/Lebanon.png',
                description: '',
            },
            {
                id: 95,
                title: 'Lesotho',
                image: 'Images/Lesotho.png',
                description: '',
            },
            {
                id: 96,
                title: 'Liberia',
                image: 'Images/Liberia.png',
                description: '',
            },
            {
                id: 97,
                title: 'Libya',
                image: 'Images/Libya.png',
                description: '',
            },
            {
                id: 98,
                title: 'Liechtenstein',
                image: 'Images/Liechtenstein.png',
                description: '',
            },
            {
                id: 99,
                title: 'Lithuania',
                image: 'Images/Lithuania.png',
                description: '',
            },
            {
                id: 100,
                title: 'Luxembourg',
                image: 'Images/Luxembourg.png',
                description: '',
            },
            {
                id: 101,
                title: 'Madagascar',
                image: 'Images/Madagascar.png',
                description: '',
            },
            {
                id: 102,
                title: 'Malawi',
                image: 'Images/Malawi.png',
                description: '',
            },
            {
                id: 103,
                title: 'Malaysia',
                image: 'Images/Malaysia.png',
                description: '',
            },
            {
                id: 104,
                title: 'Maldives',
                image: 'Images/Maldives.png',
                description: '',
            },
            {
                id: 105,
                title: 'Mali',
                image: 'Images/Mali.png',
                description: '',
            },
            {
                id: 106,
                title: 'Malta',
                image: 'Images/Malta.png',
                description: '',
            },
            {
                id: 107,
                title: 'Marshall Islands',
                image: 'Images/Marshall-Islands.png',
                description: '',
            },
            {
                id: 108,
                title: 'Mauritania.png',
                image: 'Images/Mauritania.png',
                description: '',
            },
            {
                id: 109,
                title: 'Mauritius',
                image: 'Images/Mauritius.png',
                description: '',
            },
            {
                id: 110,
                title: 'Mexico',
                image: 'Images/Mexico.png',
                description: '',
            },
            {
                id: 111,
                title: 'Micronesia',
                image: 'Images/Micronesia.png',
                description: '',
            },
            {
                id: 112,
                title: 'Moldova',
                image: 'Images/Moldova.png',
                description: '',
            },
            {
                id: 113,
                title: 'Monaco',
                image: 'Images/Monaco.png',
                description: '',
            },
            {
                id: 114,
                title: 'Mongolia',
                image: 'Images/Mongolia.png',
                description: '',
            },
            {
                id: 115,
                title: 'Montenegro',
                image: 'Images/Montenegro.png',
                description: '',
            },
            {
                id: 116,
                title: 'Morocco',
                image: 'Images/Morocco.png',
                description: '',
            },
            {
                id: 117,
                title: 'Mozambique',
                image: 'Images/Mozambique.png',
                description: '',
            },
            {
                id: 118,
                title: 'Myanmar',
                image: 'Images/Myanmar.png',
                description: '',
            },
            {
                id: 119,
                title: 'Namibia',
                image: 'Images/Namibia.png',
                description: '',
            },
            {
                id: 120,
                title: 'Nauru',
                image: 'Images/Nauru.png',
                description: '',
            },
            {
                id: 121,
                title: 'Nepal',
                image: 'Images/Nepal.png',
                description: '',
            },
            {
                id: 122,
                title: 'Netherlands',
                image: 'Images/Netherlands.png',
                description: '',
            },
            {
                id: 123,
                title: 'New Zealand',
                image: 'Images/New-Zealand.png',
                description: '',
            },
            {
                id: 124,
                title: 'Nicaragua',
                image: 'Images/Nicaragua.png',
                description: '',
            },
            {
                id: 125,
                title: 'Niger',
                image: 'Images/Niger.png',
                description: '',
            },
            {
                id: 126,
                title: 'Nigeria',
                image: 'Images/Nigeria.png',
                description: '',
            },
            {
                id: 127,
                title: 'North Korea',
                image: 'Images/North-Korea.png',
                description: '',
            },
            {
                id: 128,
                title: 'North Macedonia',
                image: 'Images/North-Macedonia.png',
                description: '',
            },
            {
                id: 129,
                title: 'Norway',
                image: 'Images/Norway.png',
                description: '',
            },
            {
                id: 130,
                title: 'Oman',
                image: 'Images/Oman.png',
                description: '',
            },
            {
                id: 131,
                title: 'Pakistan',
                image: 'Images/Pakistan.png',
                description: '',
            },
            {
                id: 132,
                title: 'Palau',
                image: 'Images/Palau.png',
                description: '',
            },
            {
                id: 133,
                title: 'Palestine',
                image: 'Images/Palestine.png',
                description: '',
            },
            {
                id: 134,
                title: 'Panama',
                image: 'Images/Panama.png',
                description: '',
            },
            {
                id: 135,
                title: 'Papua New Guinea',
                image: 'Images/Papua-New-Guinea.png',
                description: '',
            },
            {
                id: 136,
                title: 'Paraguay',
                image: 'Images/Paraguay.png',
                description: '',
            },
            {
                id: 137,
                title: 'Peru',
                image: 'Images/Peru.png',
                description: '',
            },
            {
                id: 138,
                title: 'Philippines',
                image: 'Images/Philippines.png',
                description: '',
            },
            {
                id: 139,
                title: 'Poland',
                image: 'Images/Poland.png',
                description: '',
            },
            {
                id: 140,
                title: 'Portugal',
                image: 'Images/Portugal.png',
                description: '',
            },
            {
                id: 141,
                title: 'Qatar',
                image: 'Images/Qatar.png',
                description: '',
            },
            {
                id: 142,
                title: 'Republic of Congo',
                image: 'Images/Republic-of-Congo.png',
                description: '',
            },
            {
                id: 143,
                title: 'Romania',
                image: 'Images/Romania.png',
                description: '',
            },
            {
                id: 144,
                title: 'Russia',
                image: 'Images/Russia.png',
                description: '',
            },
            {
                id: 145,
                title: 'Rwanda',
                image: 'Images/Rwanda.png',
                description: '',
            },
            {
                id: 146,
                title: 'Saint Kitts and Nevis',
                image: 'Images/Saint-Kitts-and-Nevis.png',
                description: '',
            },
            {
                id: 147,
                title: 'Saint Lucia',
                image: 'Images/St-Lucia.png',
                description: '',
            },
            {
                id: 148,
                title: 'Saint Vincent and The Grenadines',
                image: 'Images/Saint-Vincent-and-The-Grenadines.png',
                description: '',
            },
            {
                id: 149,
                title: 'Samoa',
                image: 'Images/Samoa.png',
                description: '',
            },
            {
                id: 150,
                title: 'San Marino',
                image: 'Images/San-Marino.png',
                description: '',
            },
            {
                id: 151,
                title: 'Sao Tome and Principe',
                image: 'Images/Sao-Tome-and-Principe.png',
                description: '',
            },
            {
                id: 152,
                title: 'Saudi Arabia',
                image: 'Images/Saudi-Arabia.png',
                description: '',
            },
            {
                id: 153,
                title: 'Senegal',
                image: 'Images/Senegal.png',
                description: '',
            },
            {
                id: 154,
                title: 'Serbia',
                image: 'Images/Serbia.png',
                description: '',
            },
            {
                id: 155,
                title: 'Seychelles',
                image: 'Images/Seychelles.png',
                description: '',
            },
            {
                id: 156,
                title: 'Sierra Leone',
                image: 'Images/Sierra-Leone.png',
                description: '',
            },
            {
                id: 157,
                title: 'Singapore',
                image: 'Images/Singapore.png',
                description: '',
            },
            {
                id: 158,
                title: 'Slovakia',
                image: 'Images/Slovakia.png',
                description: '',
            },
            {
                id: 159,
                title: 'Slovenia',
                image: 'Images/Slovenia.png',
                description: '',
            },
            {
                id: 160,
                title: 'Solomon Islands',
                image: 'Images/Solomon-Islands.png',
                description: '',
            },
            {
                id: 161,
                title: 'Somalia',
                image: 'Images/Somalia.png',
                description: '',
            },
            {
                id: 162,
                title: 'South Africa',
                image: 'Images/South-Africa.png',
                description: '',
            },
            {
                id: 163,
                title: 'South Korea',
                image: 'Images/South-Korea.png',
                description: '',
            },
            {
                id: 164,
                title: 'South Sudan',
                image: 'Images/South-Sudan.png',
                description: '',
            },
            {
                id: 165,
                title: 'Spain',
                image: 'Images/Spain.png',
                description: '',
            },
            {
                id: 166,
                title: 'Sri Lanka',
                image: 'Images/Sri-Lanka.png',
                description: '',
            },
            {
                id: 167,
                title: 'Sudan',
                image: 'Images/Sudan.png',
                description: '',
            },
            {
                id: 168,
                title: 'Suriname',
                image: 'Images/Suriname.png',
                description: '',
            },
            {
                id: 169,
                title: 'Sweden',
                image: 'Images/Sweden.png',
                description: '',
            },
            {
                id: 170,
                title: 'Switzerland',
                image: 'Images/Switzerland.png',
                description: '',
            },
            {
                id: 171,
                title: 'Syria',
                image: 'Images/Syria.png',
                description: '',
            },
            {
                id: 172,
                title: 'Taiwan',
                image: 'Images/Taiwan.png',
                description: '',
            },
            {
                id: 173,
                title: 'Tajikistan',
                image: 'Images/Tajikistan.png',
                description: '',
            },
            {
                id: 174,
                title: 'Tanzania',
                image: 'Images/Tanzania.png',
                description: '',
            },
            {
                id: 175,
                title: 'Thailand',
                image: 'Images/Thailand.png',
                description: '',
            },
            {
                id: 176,
                title: 'Timor Leste',
                image: 'Images/Timor-Leste.png',
                description: '',
            },
            {
                id: 177,
                title: 'Togo',
                image: 'Images/Togo.png',
                description: '',
            },
            {
                id: 178,
                title: 'Tonga',
                image: 'Images/Tonga.png',
                description: '',
            },
            {
                id: 179,
                title: 'Trinidad and Tobago',
                image: 'Images/Trinidad-and-Tobago.png',
                description: '',
            },
            {
                id: 180,
                title: 'Tunisia',
                image: 'Images/Tunisia.png',
                description: '',
            },
            {
                id: 181,
                title: 'Turkey',
                image: 'Images/Turkey.png',
                description: '',
            },
            {
                id: 182,
                title: 'Turkmenistan',
                image: 'Images/Turkmenistan.png',
                description: '',
            },
            {
                id: 183,
                title: 'Tuvalu',
                image: 'Images/Tuvalu.png',
                description: '',
            },
            {
                id: 184,
                title: 'Uganda',
                image: 'Images/Uganda.png',
                description: '',
            },
            {
                id: 185,
                title: 'Ukraine',
                image: 'Images/Ukraine.png',
                description: '',
            },
            {
                id: 186,
                title: 'United Arab Emirates',
                image: 'Images/United-Arab-Emirates.png',
                description: '',
            },
            {
                id: 187,
                title: 'United Kingdom',
                image: 'Images/United-Kingdom.png',
                description: '',
            },
            {
                id: 188,
                title: 'United States of America',
                image: 'Images/United-States-of-America.png',
                description: '',
            },
            {
                id: 189,
                title: 'Uruguay',
                image: 'Images/Uruguay.png',
                description: '',
            },
            {
                id: 190,
                title: 'Uzbekistan',
                image: 'Images/Uzbekistan.png',
                description: '',
            },
            {
                id: 191,
                title: 'Vanuatu',
                image: 'Images/Vanuatu.png',
                description: '',
            },
            {
                id: 192,
                title: 'Vatican City',
                image: 'Images/Vatican-City.png',
                description: '',
            },
            {
                id: 193,
                title: 'Venezuela',
                image: 'Images/Venezuela.png',
                description: '',
            },
            {
                id: 194,
                title: 'Vietnam',
                image: 'Images/Vietnam.png',
                description: '',
            },
            {
                id: 195,
                title: 'Yemen',
                image: 'Images/Yemen.png',
                description: '',
            },
            {
                id: 196,
                title: 'Zambia',
                image: 'Images/Zambia.png',
                description: '',
            },
            {
                id: 197,
                title: 'Zimbabwe',
                image: 'Images/Zimbabwe.png',
                description: '',
            },
        ],
    },
    computed: {
        filteredCards() {
            return this.cards.filter((card) => {
                return card.title.toLowerCase().includes(this.searchQuery.toLowerCase());
            });
        },
    },
    methods: {
        showModal(card) {
            this.selectedCard = card;
            this.descriptionInput = card.description;
        },
        closeModal() {
            this.selectedCard = null;
        },
        saveCard() {
            if (this.selectedCard) {
                this.selectedCard.description = this.descriptionInput;

                const sharedCard = indexApp.upcomingTrips.find((card) => card.id === this.selectedCard.id);
                if (sharedCard) {
                    sharedCard.description = this.descriptionInput;
                }

                this.descriptionInput = '';
                this.selectedCard = null;
            }
        },
    },
});







